import"dotenv/config";import express from"express";import http from"node:http";import fs from"node:fs";import path from"node:path";import{fileURLToPath}from"node:url";import{Server}from"socket.io";import{QuizEngine,Question}from"./quiz-engine.js";import{connectTikFinity}from"./tikfinity.js";import{ElevenLabsTTS}from"./tts.js";
const __dirname=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(__dirname,".."),questions=JSON.parse(fs.readFileSync(path.join(root,"data/questions.json"),"utf8")) as Question[],engine=new QuizEngine(questions,10),tts=new ElevenLabsTTS(root);
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(root,"public")));app.use("/tts-cache",express.static(path.join(root,".cache","tts")));app.use(express.json());let tikfinityStatus="connecting",lastLeader="",speechChain=Promise.resolve();
const broadcast=()=>io.emit("state",{...engine.state(),tikfinityStatus,ttsStatus:tts.enabled?"elevenlabs":"browser-fallback"});
function speak(text:string){speechChain=speechChain.then(async()=>{if(!tts.enabled){io.emit("speak",{text});return}try{const a=await tts.audioFor(text);console.log("TTS:",a.cached?"CACHE":"GENERATED",text.slice(0,55));io.emit("audio",{url:"/tts-cache/"+path.basename(a.file)});await new Promise(r=>setTimeout(r,250))}catch(e){console.error("ElevenLabs TTS failed:",e);io.emit("speak",{text})}})}
function questionSpeech(q:Question){let t=q.text;if(q.options)t+=" "+Object.entries(q.options).map(([k,v])=>k+", "+v).join(". ")+". ";return t+" Ai 10 secunde!"}
io.on("connection",socket=>{socket.emit("state",{...engine.state(),tikfinityStatus,ttsStatus:tts.enabled?"elevenlabs":"browser-fallback"});socket.on("answer",(p:{username?:string;answer?:string})=>{if(p.username&&p.answer){engine.submitRaw(p.username.trim().slice(0,30),p.answer);broadcast()}})});
connectTikFinity((u,c)=>{engine.submitRaw(u,c);broadcast()},s=>{tikfinityStatus=s;console.log("TikFinity:",s.toUpperCase());broadcast()});
setInterval(()=>{const s=engine.state();if(s.phase!=="question")return;if(s.secondsLeft<=0){const q=engine.current,milestones=engine.reveal();broadcast();const answer=q.options?.[String(q.answer)]??String(q.answer);speak("Răspunsul corect este "+answer+".");const leader=engine.leader();if(milestones[0])speak(milestones[0]);if(leader&&leader.username!==lastLeader){if(lastLeader)speak("Avem un nou lider! "+leader.username+" este pe primul loc cu "+leader.score+" de puncte.");lastLeader=leader.username}setTimeout(()=>{engine.next();broadcast();speak(questionSpeech(engine.current))},4000)}else{engine.tick();broadcast()}},1000);
server.listen(3000,()=>{console.log("Quiz: http://localhost:3000");console.log("TTS:",tts.enabled?"ELEVENLABS":"BROWSER FALLBACK");setTimeout(()=>speak(questionSpeech(engine.current)),1200)});